project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "www/CSAFE_Tools_handwriter.png"
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: "Get Started"
        file: get-started.qmd
      - text: "Learn More"
        file: learn-more.qmd
      - text: "Permitted Use"
        file: permitted-use.qmd
      - text: Contact
        file: contact.qmd
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriter
        aria-label: handwriter GitHub

format:
  html:
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: right
    code-fold: true
    code-tools: true
    code-summary: "Show code"
    code-overflow: wrap
    fig-width: 7
    fig-height: 5

editor: visual

