project:
  type: website
  output-dir: docs

website:
  title: "handwriter"
  navbar:
    logo: "www/CSAFE_Tools_handwriter.png"
    search: true
    left:
      - text: Home
        file: index.qmd
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriter
        aria-label: handwriter GitHub

format:
  html:
    css: csafe.css
    toc: true
    toc-depth: 2
    toc-location: left

editor: visual

